### Get SPECIFIC TASK
GET http://127.0.0.1:8000/api/tasks/3
Accept: application/json

### Get ALL TASKS
GET http://localhost:8000/api/tasks
Accept: application/json

### POST A TASK
POST http://localhost:8000/api/tasks
Content-Type: application/json

{
    "title": "BeyBlades",
    "description": "This should be a thing",
    "status": "in_progress"
}


### UPDATE A TASK
PUT http://localhost:8000/api/tasks/3
Content-Type: application/json

{
    "title": "fir",
    "description": "No die",
    "status": "in_progress"
}

### DELETE A TASK
DELETE http://localhost:8000/api/tasks/3
Accept: application/json

